### PR TITLE
Fix: #902 'Problem using SVG with LinearGradient when exporting to PNG' issue.

### LINKED ISSUE #902: Problem using SVG with LinearGradient when exporting to PNG
#### Description
LinearGradient is not correct.
here is the code of it
image

SVG
image
PNG
image

#### Used Versions

Net 6.0 SVG 3.3.0 on windows

### PR DESCRIPTION
**Pull request by H1Gdev**
#### Reference Issue

Fixes #902

Ref. #224 and #314.

#### Any other comments?

- rounding error with float values.
- [The elements in this array are represented by float values between 0.0f and 1.0f](https://docs.microsoft.com/ja-jp/dotnet/api/system.drawing.drawing2d.colorblend.positions#remarks)

### CODE REVIEW

**Comment by stubbfel** [comment]
@mrbean-bremen may it is possible that this fix, "re enable" issue #224? 
Because since 3.4.0 i got this exception, when i try to "export" some svg files as png.  
With 3.3.0 it works the "export" works fine

**Comment by H1Gdev** [comment]
@stubbfel 

What SVG files do error occur with ?

**Comment by stubbfel** [comment]
@H1Gdev  like this
```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 16.0.4, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Test_Gradient_Svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
	 x="0px" y="0px" width="105px" height="300px" viewBox="0 0 105 300" enable-background="new 0 0 105 300" xml:space="preserve">
<linearGradient id="Grad_1" gradientUnits="userSpaceOnUse" x1="-166.498" y1="-43.168" x2="121.502" y2="210.832">
	<stop  offset="0" style="stop-color:#F1F1F1"/>
	<stop  offset="1" style="stop-color:#3C3C3B"/>
</linearGradient>
<path id="Grad_2" fill="url(#Grad_1)" stroke="#858594" stroke-width="0.75" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" d=""/>
</svg>
```
file: [test_gradient.svg](https://user-images.githubusercontent.com/4604462/158658674-106d3fc0-a890-4ee5-bad2-17b827aacafe.svg)

note: this file was created only to demonstrate the issue

**Comment by H1Gdev** [comment]
This is another cause.
I will consider how to fix it.

**Pull request merged**
