### PR TITLE
Converted to HTTPS links in README

### PR DESCRIPTION
**Pull request by 304NotModified**
#### What does this implement/fix? Explain your changes.
Changed http to http**s** links.

#### Any other comments?
The https://svg.codeplex.com/ link is dead (but it's https already ;)) - maybe remove it?

### CODE REVIEW

**Review by mrbean-bremen — APPROVED** [review]
Thanks!

**Comment by mrbean-bremen** [comment]
> The https://svg.codeplex.com/ link is dead (but it's https already ;)) - maybe remove it?

Yes, make sense. Can you add this to the PR?

**Comment by 304NotModified** [comment]
Only the link or the whole paragraph?

**Comment by mrbean-bremen** [comment]
> Only the link or the whole paragraph?

Only the link, the paragraph is still valid.

**Comment by 304NotModified** [comment]
Done!

**Comment by 304NotModified** [comment]
@mrbean-bremen maybe also remove the link in the "about" of this repo?

**Comment by mrbean-bremen** [comment]
Good point, done!

**Pull request merged**
