### PR TITLE
Parse performance optimizations

### PR DESCRIPTION
**Pull request by wieslawsoltes**
Optimizes performance and memory usage for Parse operations.

This PR has been split and summary moved to tracking issue #802

Split status:
- [x] Source/DataTypes/SvgNumberCollection.cs #807
- [x] Source/DataTypes/SvgPointCollection.cs #808
- [x] Source/DataTypes/SvgUnitCollection.cs #805
- [x] Source/DataTypes/SvgUnitConverter.cs #805
- [x] Source/Helpers/FloatParser.cs #801
- [x] Source/Helpers/StringSplitEnumerator.cs #801
- [x] Source/Painting/SvgColourConverter.cs #806
- [x] Source/Paths/CoordinateParser.cs #804
- [x] Source/Paths/SvgPathBuilder.cs #810
- [x] Source/Transforms/SvgTransformConverter.cs #809
- [x] Tests/Svg.Benchmark/CoordinateParserBenchmarks.cs #804
- [x] Tests/Svg.Benchmark/Program.cs #803
- [x] Tests/Svg.Benchmark/README.md #803
- [x] Tests/Svg.Benchmark/Svg.Benchmark.csproj #803
- [x] Tests/Svg.Benchmark/SvgColourConverterBenchmarks.cs #806
- [x] Tests/Svg.Benchmark/SvgDocumentBenchmarks.cs #803
- [x] Tests/Svg.Benchmark/SvgNumberCollectionConverterBenchmarks.cs #807
- [x] Tests/Svg.Benchmark/SvgPathBuilderBenchmarks.cs #810
- [x] Tests/Svg.Benchmark/SvgPointCollectionConverterBenchmarks.cs #808
- [x] Tests/Svg.Benchmark/SvgTransformConverter.cs (only rename) #803
- [x] Tests/Svg.Benchmark/SvgTransformConverterBenchmarks.cs #809
- [x] Tests/Svg.Benchmark/SvgUnitCollectionConverterBenchmarks.cs #805
- [x] Tests/Svg.Benchmark/SvgUnitConverterBenchmarks.cs #805
- [x] Tests/Svg.UnitTests/MarkerEndTest.cs #810
- [x] Tests/Svg.UnitTests/PerformanceTest.cs

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
@wieslawsoltes - just a suggestion: I would propose to split this PR into several PRs, e.g. get the current one working, let it review (I'm hoping for @inforithmics here) and merge it and go for the next bunch. This way reviewing will be easier, you have stable versions you can rely on, and there are less possible conflict with other changes.

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes - just a suggestion: I would propose to split this PR into several PRs, e.g. get the current one working, let it review (I'm hoping for @inforithmics here) and merge it and go for the next bunch. This way reviewing will be easier, you have stable versions you can rely on, and there are less possible conflict with other changes.

That is good idea, I will try to finish the current work and continue the rest in another PRs.

**Comment by wieslawsoltes** [comment]
Split status:
- [ ] Source/DataTypes/SvgNumberCollection.cs
- [ ] Source/DataTypes/SvgPointCollection.cs
- [ ] Source/DataTypes/SvgUnitCollection.cs
- [ ] Source/DataTypes/SvgUnitConverter.cs
- [ ] Source/Helpers/FloatParser.cs #801
- [ ] Source/Helpers/StringSplitEnumerator.cs #801
- [ ] Source/Painting/SvgColourConverter.cs
- [ ] Source/Paths/CoordinateParser.cs
- [ ] Source/Paths/SvgPathBuilder.cs
- [ ] Source/Transforms/SvgTransformConverter.cs
- [ ] Tests/Svg.Benchmark/CoordinateParserBenchmarks.cs
- [ ] Tests/Svg.Benchmark/Program.cs
- [ ] Tests/Svg.Benchmark/README.md
- [ ] Tests/Svg.Benchmark/Svg.Benchmark.csproj
- [ ] Tests/Svg.Benchmark/SvgColourConverterBenchmarks.cs
- [ ] Tests/Svg.Benchmark/SvgDocumentBenchmarks.cs
- [ ] Tests/Svg.Benchmark/SvgNumberCollectionConverterBenchmarks.cs
- [ ] Tests/Svg.Benchmark/SvgPathBuilderBenchmarks.cs
- [ ] Tests/Svg.Benchmark/SvgPointCollectionConverterBenchmarks.cs
- [ ] Tests/Svg.Benchmark/SvgTransformConverter.cs (rename)
- [ ] Tests/Svg.Benchmark/SvgTransformConverterBenchmarks.cs
- [ ] TTests/Svg.Benchmark/SvgUnitCollectionConverterBenchmarks.cs
- [ ] Tests/Svg.Benchmark/SvgUnitConverterBenchmarks.cs
- [ ] Tests/Svg.UnitTests/MarkerEndTest.cs
- [ ] Tests/Svg.UnitTests/PerformanceTest.cs

**Comment by wieslawsoltes** [comment]
Closing this as changes have been split into smaller PRs

**Pull request closed without merging**
