### PR TITLE
Solving bug of error resolution "ul ol+li{fill:#000000;font-family:ZWBIQX+HelveticaUnicodeMS;}"

### PR DESCRIPTION
**Pull request by mccj**
#### What does this implement/fix? Explain your changes.
1.解决解析 `ul ol+li{fill:#000000;font-family:ZWBIQX+HelveticaUnicodeMS;}` 错误的问题
2.解决 style 样式内字体无法解析的问题

### CODE REVIEW

**Comment by mccj** [comment]
Converting PDF to SVG file with FreeSpire.PDF generates the following code
`<text style="fill:#000000;font-family:AAAAAA+WenQuanYiMicroHei-0;" font-size="7" x="132.8691" y="22.13528">B</text>`
Style symbol `+` cannot be parsed at present.

**Comment by mccj** [comment]
Converting PDF to SVG file with FreeSpire.PDF generates the following code
```
    <defs>
        <style type="text/css">
            <![CDATA[
            @font-face {
                font-family: 'KUTEMH+ArialUnicodeMS';
                src: url("data:font/truetype;charset=utf-8;base64,AAEA....");
            }
            ]] >
        </style>
    </defs>
```
Font cannot resolve rendering problem

**Comment by mccj** [comment]
Here is a sample file
[Example.zip](https://github.com/vvvv/SVG/files/3746120/Example.zip)

**Comment by mrbean-bremen** [comment]
@mccj - is this a replacement for #574? Also, could you please add an English description to the PR? Not all of us speak Chinese...

**Comment by mrbean-bremen** [comment]
@H1Gdev - can you please have a look if this make sense, or shall be close that? Got no response here...

**Comment by H1Gdev** [comment]
@mrbean-bremen 

This PR needs to be separated.
1. Allow `+` for font-family value
1. Add font to PrivateFontCollection

#### Allow `+` for font-family value

We are working to use `ExCSS_Core` in PR #596.
So, I think it is efficient to create PR in `ExCSS_Core`.

#### Add font to PrivateFontCollection

This library has not been able to manage `PrivateFontCollection`s now...
https://github.com/vvvv/SVG/search?l=C%23&q=PrivateFontCollection

I think that we cannot add more `PrivateFontCollection`.

**Comment by mrbean-bremen** [comment]
Aged away and no response from OP - closing.

**Pull request closed without merging**
