### PR TITLE
Fixes localized family names in SvgFontManager.

### PR DESCRIPTION
**Pull request by H1Gdev**
#### Reference Issue

Ref. #706, #723

#### Any other comments?

Issue that occurred in #723.

### CODE REVIEW

**Comment by H1Gdev** [comment]
I modified files so that test would catch it.

**Comment by H1Gdev** [comment]
@mrbean-bremen 

test is no longer passing...

Is there a way to install fonts in GitHub Workflow ?
If not, I will skip this test.

**Comment by mrbean-bremen** [comment]
> Is there a way to install fonts in GitHub Workflow ?

I have no idea - better to skip the test for now, and maybe add an issue for installing a font in the CI environment.

**Comment by H1Gdev** [comment]
@mrbean-bremen 

Changed test to use font installed in Workflow.

**Review by mrbean-bremen — APPROVED** [review]

**Pull request merged**
