### PR TITLE
Take into account of parent transforms

### PR DESCRIPTION
**Pull request by Happypig375**

### CODE REVIEW

**Comment by Happypig375** [comment]
@mrbean-bremen Re-run?

**Comment by H1Gdev** [comment]
What kind of `SVG` will this PR improve ?

**Comment by Happypig375** [comment]
@H1Gdev 
```svg
<svg viewBox="0 0 100 100">
  <text transform="translate(10 30)">
    <tspan id="target">ABC</tspan>
  </text>
</svg>
```
Bounds of `tspan` from view box should match `text`

**Comment by H1Gdev** [comment]
Thanks.

What happens with this SVG ?
```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="100" height="100">
  <text>
    <tspan transform="translate(10 30)">ABC</tspan>
  </text>
</svg>
```

Many major browsers don't show anything for this SVG. (`transform` in \<tspan\> seems to be ignored.)

**Comment by Happypig375** [comment]
<tspan> doesn't support transforms by itself, correct. But its bounds should use its parent transforms to result in same bounds for the <text> and <tspan> elements since they do represent the same text at the same location.

**Comment by H1Gdev** [comment]
It doesn't seem to work properly with latest master, can it be fixed by merging this PR ?

**Comment by Happypig375** [comment]
Yes, this is what I aim to fix.

**Comment by H1Gdev** [comment]
It doesn't seem to be fixed...
This SVG should not show anything because \<tspan\> `transform` is invalid.

**Comment by Happypig375** [comment]
In this case, it's the problem of the parser, and Bounds just takes information from the object tree. Out of scope.

**Comment by Happypig375** [comment]
```svg
<svg viewBox="0 0 100 100">
  <text transform="translate(10 30)">
    <tspan id="target">ABC</tspan>
  </text>
</svg>
```
This PR fixes this, and this only.

**Comment by Happypig375** [comment]
Hmm, actually this issue may exist across different element types, not just \<tspan>.

**Comment by Happypig375** [comment]
Superceded by #945

**Pull request closed without merging**
