### PR TITLE
Update from .NET 5 to .NET 6.

### PR DESCRIPTION
**Pull request by H1Gdev**
#### Reference Issue

Ref. PR #1045 

#### What does this implement/fix? Explain your changes.

Change order of values in \<TargetFrameworks\>.

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
Can you please explain why this is needed?

**Comment by H1Gdev** [comment]
SVGViewer etc. will start using the leftmost framework.
I thought it would be better to start with the latest framework rather than net462 starting by default.

**Comment by mrbean-bremen** [comment]
You mean if you have compiled several version and start them inside Visual Studio? Isn't the target shown and selectable in VS? (I'm usually using Rider instead of VS)

**Comment by H1Gdev** [comment]
It is possible to choose which framework to run.
I think default framework is `.NET` rather than `.NET Framework`.

**Comment by mrbean-bremen** [comment]
> I think default framework is .NET rather than .NET Framework.

In this case, what difference does the change make? I'm obviously missing something...

**Comment by H1Gdev** [comment]
SVGViewer

master
master

PR #1048 
pr1048

**Comment by mrbean-bremen** [comment]
Ok, I see, thank you. It's a bit of a cosmetic issue, but I agree that's a bit more convenient.

**Review by mrbean-bremen — APPROVED** [review]

**Pull request merged**
